modLoader="javafml" #junkloader

loaderVersion="[36.1,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="CC-BY-4.0 License"

issueTrackerURL="https://github.com/KosmX/emotes/issues" #optional

[[mods]] #mandatory
# The modid of the mod
modId="emotecraft"

version="${version}"

displayName="Emotecraft"

#displayURL="https://kosmx.gitbook.io/emotecraft/"
#Forge menu was always trying to open this.

logoFile="emotecraft_mod_logo.png" #optional

authors="KosmX" #optional

description="Play emotes in Minecraft\nOpen the menu to setup your fast-choose wheel\n\nYou can add custom emotes, and you can play these even if nobody else has them\n\nSpecial thanks:\nOrangeKale64 for creating emotes and help in the UI design\nOrsond for inspiring me and providing CollarMC (He called the mod EmoteX)\narchitectury for the Forge build tools"
