# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ development ]

jobs:
  build:
    strategy:
      matrix:
        java: [1.8, 11, 16]
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: configure gradle
      uses: gradle/wrapper-validation-action@v1
      with:
        java-version: ${{matrix.java}}
    - name: Grant execute permission for gradlew
      if: ${{ runner.os != 'Windows' }
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
